---
galaxy_info:
  author: Rob Cowie
  description: Ansible profile role for developers
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: Darwin
      versions:
        - all
  categories:
    - system
dependencies:
  - roderik.superlumic-computername
  - roderik.superlumic-cli
  - roderik.superlumic-homebrew
  - roderik.superlumic-sublimetext
  - roderik.superlumic-vim
